-- =============================================================================
-- SUPABASE SCHEMA REFERENCE: Music Collection Database
-- =============================================================================
-- This file is a READ-ONLY documentation artifact. It is NOT intended to be
-- run against the live database. It is the single authoritative reference for
-- every table, column, constraint, function, trigger, and grant that exists
-- on the deployed Supabase public schema today.
--
-- Source of truth: generated by querying the live Supabase database via
-- information_schema, pg_trigger, pg_proc, pg_indexes, and role_table_grants.
--
-- Database:  Supabase project <project-ref>
-- Host:      <your-project>.pooler.supabase.com:5432
-- Schema:    public (all 11 tables, 11 functions, 17 triggers)
--
-- ASSUMED SEED (separate file):
--   seed_genres_descriptors.sql  -- genre nodes + genre tree + descriptor
--                                  nodes + descriptor tree, extracted live.
--   Artists and records are NOT seeded here; they are created at runtime
--   by the Flutter web app.
-- =============================================================================


-- =============================================================================
-- TABLE OF CONTENTS
-- =============================================================================
--  1.  artists                     (entity - artist name)
--  2.  records                     (entity - music release)
--  3.  genres                      (entity - genre taxonomy node)
--  4.  descriptors                 (entity - descriptor taxonomy node)
--  5.  record_artists              (junction - record <-> artist)
--  6.  record_genres               (junction - record <-> genre)
--  7.  record_descriptors          (junction - record <-> descriptor)
--  8.  record_streaming            (junction - record <-> streaming service)
--  9.  genre_hierarchy             (tree edge - genre parent -> child)
-- 10.  descriptor_hierarchy        (tree edge - descriptor parent -> child)
-- 11.  audit_log                   (system - immutable change log)
--
-- 12. FUNCTIONS                    (11 PL/pgSQL functions)
-- 13. TRIGGERS                     (17 triggers wired to data tables)
-- 14. GRANTS                       (anon / authenticated / service_role)
-- 15. RLS NOTES                    (audit_log hard-lock, currently deferred)
-- =============================================================================


-- =============================================================================
-- 1. artists
-- =============================================================================
-- Unique artist names. The denormalized ref_count is maintained by triggers
-- (see section 12 fn_record_artists_ref_count).
CREATE TABLE artists (
    artist_id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    artist_name TEXT NOT NULL UNIQUE,
    ref_count   INTEGER NOT NULL DEFAULT 0
);


-- =============================================================================
-- 2. records
-- =============================================================================
-- A single music release (album / EP / single / mixtape / etc.).
--
-- release_date_mask encoding (day*4 + month*2 + year):
--   0 = no date volunteered;  1 = year only;  3 = year+month;  7 = full date.
-- The app guarantees only 0/1/3/7 ever occur (day implies month implies year).
-- release_date always stores the full canonical YYYY-MM-DD Postgres DATE
-- (with unknown components filled from the month=07 convention) so that date
-- math, sorting, and grouping work normally. The mask drives display only.
CREATE TABLE records (
    record_id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    record_name        TEXT NOT NULL,
    record_type        TEXT,
    release_date       DATE,
    date_added         TEXT,
    comments           TEXT,
    status             BOOLEAN DEFAULT FALSE,
    release_date_mask  SMALLINT NOT NULL DEFAULT 0
);


-- =============================================================================
-- 3. genres
-- =============================================================================
-- Every genre taxonomy node. The three denormalized counters are maintained by
-- triggers (see section 12 for algorithms):
--   ref_count        = # of records directly tagged with this genre
--   children_count   = # of descendant nodes in this genre's entire subtree
--   total_ref_count  = # of records that reference this genre OR any descendant
CREATE TABLE genres (
    genre_id        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    genre_name      TEXT NOT NULL UNIQUE,
    ref_count       INTEGER NOT NULL DEFAULT 0,
    children_count  INTEGER NOT NULL DEFAULT 0,
    total_ref_count INTEGER NOT NULL DEFAULT 0
);


-- =============================================================================
-- 4. descriptors
-- =============================================================================
-- Same structure as genres. Denormalized counters maintained by triggers.
CREATE TABLE descriptors (
    descriptor_id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descriptor_name TEXT NOT NULL UNIQUE,
    ref_count       INTEGER NOT NULL DEFAULT 0,
    children_count  INTEGER NOT NULL DEFAULT 0,
    total_ref_count INTEGER NOT NULL DEFAULT 0
);


-- =============================================================================
-- 5. record_artists  (junction)
-- =============================================================================
-- Links records to artists. The same artist can appear in multiple rows of the
-- same record with different artist_order (e.g. primary vs. featured).
CREATE TABLE record_artists (
    record_id    INTEGER NOT NULL REFERENCES records(record_id),
    artist_id    INTEGER NOT NULL REFERENCES artists(artist_id),
    artist_order INTEGER NOT NULL,
    PRIMARY KEY (record_id, artist_id, artist_order)
);


-- =============================================================================
-- 6. record_genres  (junction)
-- =============================================================================
-- Links records to genres. genre_order preserves the order in which genres
-- were assigned by the user (first genre = primary).
CREATE TABLE record_genres (
    record_id   INTEGER NOT NULL REFERENCES records(record_id),
    genre_id    INTEGER NOT NULL REFERENCES genres(genre_id),
    genre_order INTEGER NOT NULL,
    PRIMARY KEY (record_id, genre_id, genre_order)
);


-- =============================================================================
-- 7. record_descriptors  (junction)
-- =============================================================================
-- Links records to descriptors. descriptor_order preserves user-assigned order.
CREATE TABLE record_descriptors (
    record_id        INTEGER NOT NULL REFERENCES records(record_id),
    descriptor_id    INTEGER NOT NULL REFERENCES descriptors(descriptor_id),
    descriptor_order INTEGER NOT NULL,
    PRIMARY KEY (record_id, descriptor_id, descriptor_order)
);


-- =============================================================================
-- 8. record_streaming  (junction)
-- =============================================================================
-- Links records to streaming services. service_url may be NULL for local/physical
-- media or services without deep-link support. A single record can have multiple
-- services, each identified by (record_id, service_name).
CREATE TABLE record_streaming (
    record_id    INTEGER NOT NULL REFERENCES records(record_id),
    service_name VARCHAR NOT NULL,
    service_url  TEXT,
    PRIMARY KEY (record_id, service_name)
);


-- =============================================================================
-- 9. genre_hierarchy  (tree edges)
-- =============================================================================
-- Each row is one parent->child edge of the genre taxonomy tree. A genre can
-- have multiple parents (DAG, not strictly a tree) and multiple children.
-- No self-loops are allowed (enforced by app logic, not a DB constraint).
CREATE TABLE genre_hierarchy (
    parent_genre_id INTEGER NOT NULL REFERENCES genres(genre_id),
    child_genre_id  INTEGER NOT NULL REFERENCES genres(genre_id),
    PRIMARY KEY (parent_genre_id, child_genre_id)
);


-- =============================================================================
-- 10. descriptor_hierarchy  (tree edges)
-- =============================================================================
-- Same structure as genre_hierarchy, for the descriptor taxonomy.
CREATE TABLE descriptor_hierarchy (
    parent_descriptor_id INTEGER NOT NULL REFERENCES descriptors(descriptor_id),
    child_descriptor_id  INTEGER NOT NULL REFERENCES descriptors(descriptor_id),
    PRIMARY KEY (parent_descriptor_id, child_descriptor_id)
);


-- =============================================================================
-- 11. audit_log
-- =============================================================================
-- Immutable append-only change log. Every data table has an AFTER trigger that
-- calls fn_audit_log(). The function is SECURITY DEFINER (bypasses RLS) and
-- FAIL-SOFT (never blocks the caller). Records and junction tables are skipped
-- by the trigger function (they are logged by the app as whole-tuple entries
-- via RecordAuditLogger).
--
-- The audit_log hard-lock RLS policy (INSERT-only, no SELECT/UPDATE/DELETE for
-- anon/authenticated) is currently DEFERRED -- see section 15.
CREATE TABLE audit_log (
    log_id     INTEGER DEFAULT nextval('audit_log_log_id_seq'::regclass) NOT NULL PRIMARY KEY,
    action     TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id  INTEGER,
    details    JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    origin_tab TEXT,
    device     TEXT
);

-- The identity sequence for audit_log.log_id:
-- CREATE SEQUENCE IF NOT EXISTS audit_log_log_id_seq AS INTEGER START 1;


-- =============================================================================
-- INDEXES (29 total, live-verified)
-- =============================================================================
-- Unique constraints (serve double duty as search indexes):
CREATE UNIQUE INDEX artists_artist_name_key      ON artists    USING btree (artist_name);
CREATE UNIQUE INDEX genres_genre_name_key         ON genres     USING btree (genre_name);
CREATE UNIQUE INDEX descriptors_descriptor_name_key ON descriptors USING btree (descriptor_name);

-- Primary key indexes (already created by PRIMARY KEY constraints above,
-- listed here for completeness / pg_dump parity):
-- artists_pkey, records_pkey, genres_pkey, descriptors_pkey,
-- record_artists_pkey, record_genres_pkey, record_descriptors_pkey,
-- record_streaming_pkey, genre_hierarchy_pkey, descriptor_hierarchy_pkey,
-- audit_log_pkey

-- Search / query indexes:
CREATE INDEX idx_artist_name           ON artists    USING btree (artist_name);
CREATE INDEX idx_genre_name            ON genres     USING btree (genre_name);
CREATE INDEX idx_descriptor_name       ON descriptors USING btree (descriptor_name);
CREATE INDEX idx_record_name           ON records    USING btree (record_name);
CREATE INDEX idx_record_artists_artist ON record_artists    USING btree (artist_id);
CREATE INDEX idx_record_artists_record ON record_artists    USING btree (record_id);
CREATE INDEX idx_record_genres_genre   ON record_genres     USING btree (genre_id);
CREATE INDEX idx_record_genres_record  ON record_genres     USING btree (record_id);
CREATE INDEX idx_record_descriptors_descriptor ON record_descriptors USING btree (descriptor_id);
CREATE INDEX idx_record_descriptors_record     ON record_descriptors USING btree (record_id);

-- Audit log indexes:
CREATE INDEX idx_audit_log_action     ON audit_log USING btree (action);
CREATE INDEX idx_audit_log_created_at ON audit_log USING btree (created_at);
CREATE INDEX idx_audit_log_record_id  ON audit_log USING btree (record_id);
CREATE INDEX idx_audit_log_table_name ON audit_log USING btree (table_name);


-- =============================================================================
-- 12. FUNCTIONS  (11 PL/pgSQL functions)
-- =============================================================================
-- The ref_count / children_count / total_ref_count denormalized columns on
-- artists, genres, and descriptors are maintained by a set of trigger functions.
-- Their exact algorithms are:
--
--   ref_count (direct):
--     Counted by fn_record_artists_ref_count / fn_record_genres_ref_count /
--     fn_record_descriptors_ref_count. Each function increments/decrements the
--     counter on the parent entity row when a junction row is INSERTed/DELETEd.
--     formula:  ref_count = SELECT COUNT(*) FROM record_<entity>s
--                         WHERE <entity>_id = THIS.id
--
--   children_count (descendant):
--     Maintained by fn_genre_hierarchy_children / fn_descriptor_hierarchy_children.
--     On INSERT of a hierarchy edge (parent->child): walk up from the new child's
--     parent to ALL of its ancestors (via get_genre_ancestors /
--     get_descriptor_ancestors, which uses a recursive CTE walking up the tree).
--     Increment children_count by 1 on each ancestor AND on the parent itself.
--     On DELETE, the same loop decrements. The effect: every ancestor of a parent
--     "sees" the child (and all its transitive descendants) in its children_count.
--
--   total_ref_count (inherited):
--     Maintained by fn_record_genres_refs / fn_record_descriptors_refs. On INSERT
--     of a junction row (e.g. record tagged with genre X), walk UP from X through
--     all ancestors of X (via the recursive ancestor CTE) AND include X itself.
--     Increment total_ref_count by 1 on each. On DELETE, the same loop decrements.
--     The effect: a record tagged with a leaf genre automatically counts toward
--     every ancestor genre's total_ref_count.


-- ---- 12a. fn_audit_log() ----
-- SECURITY DEFINER: runs as the function owner, bypassing RLS. FAIL-SOFT:
-- if logging fails, raises WARNING and lets the data write proceed.
-- Skips records + junction tables (logged by the app instead).
-- Reads x-origin-tab / x-device from PostgREST request headers.
-- UPDATE is suppressed when the ONLY changed columns are the derived counters
-- (ref_count / total_ref_count / children_count) to avoid noise in the log.
CREATE OR REPLACE FUNCTION fn_audit_log()
RETURNS TRIGGER AS $$
DECLARE
  request_headers JSONB;
  origin_tab      TEXT;
  device          TEXT;
  subject_id      INT;
  log_details     JSONB;
  name_key        TEXT;
  friend_name     TEXT;
BEGIN
  request_headers := '{}'::jsonb;
  origin_tab := NULL;
  device := NULL;
  BEGIN
    request_headers := COALESCE(
      NULLIF(current_setting('request.headers', true), '')::jsonb,
      '{}'::jsonb
    );
    origin_tab := NULLIF(request_headers->>'x-origin-tab', '');
    device     := NULLIF(request_headers->>'x-device', '');
  EXCEPTION WHEN OTHERS THEN
    request_headers := '{}'::jsonb;
    origin_tab := NULL;
    device := NULL;
  END;

  IF TG_TABLE_NAME IN (
      'records',
      'record_artists',
      'record_genres',
      'record_descriptors',
      'record_streaming'
  ) THEN
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  END IF;

  name_key := NULL;
  friend_name := NULL;
  CASE TG_TABLE_NAME
    WHEN 'records'              THEN subject_id := COALESCE(NEW.record_id, OLD.record_id);
    WHEN 'artists'              THEN subject_id := COALESCE(NEW.artist_id, OLD.artist_id);
    WHEN 'genres'               THEN subject_id := COALESCE(NEW.genre_id, OLD.genre_id);
    WHEN 'descriptors'          THEN subject_id := COALESCE(NEW.descriptor_id, OLD.descriptor_id);
    WHEN 'record_artists'       THEN
      subject_id := COALESCE(NEW.record_id, OLD.record_id);
      name_key := 'artist_name';
      friend_name := (SELECT artist_name FROM artists WHERE artist_id = COALESCE(NEW.artist_id, OLD.artist_id));
    WHEN 'record_genres'        THEN
      subject_id := COALESCE(NEW.record_id, OLD.record_id);
      name_key := 'genre_name';
      friend_name := (SELECT genre_name FROM genres WHERE genre_id = COALESCE(NEW.genre_id, OLD.genre_id));
    WHEN 'record_descriptors'   THEN
      subject_id := COALESCE(NEW.record_id, OLD.record_id);
      name_key := 'descriptor_name';
      friend_name := (SELECT descriptor_name FROM descriptors WHERE descriptor_id = COALESCE(NEW.descriptor_id, OLD.descriptor_id));
    WHEN 'record_streaming'     THEN
      subject_id := COALESCE(NEW.record_id, OLD.record_id);
      name_key := 'service_name';
      friend_name := COALESCE(NEW.service_name, OLD.service_name);
    WHEN 'genre_hierarchy'      THEN
      subject_id := COALESCE(NEW.child_genre_id, OLD.child_genre_id);
      name_key := 'genre_name';
      friend_name := (SELECT genre_name FROM genres WHERE genre_id = COALESCE(NEW.child_genre_id, OLD.child_genre_id));
    WHEN 'descriptor_hierarchy' THEN
      subject_id := COALESCE(NEW.child_descriptor_id, OLD.child_descriptor_id);
      name_key := 'descriptor_name';
      friend_name := (SELECT descriptor_name FROM descriptors WHERE descriptor_id = COALESCE(NEW.child_descriptor_id, OLD.child_descriptor_id));
    ELSE subject_id := NULL;
  END CASE;

  IF TG_OP = 'INSERT' THEN
    log_details := jsonb_build_object('inserted', to_jsonb(NEW));
  ELSIF TG_OP = 'UPDATE' THEN
    IF (to_jsonb(OLD) - 'ref_count' - 'total_ref_count' - 'children_count') =
       (to_jsonb(NEW) - 'ref_count' - 'total_ref_count' - 'children_count') THEN
      RETURN NEW;
    END IF;
    log_details := jsonb_build_object('before', to_jsonb(OLD), 'after', to_jsonb(NEW));
  ELSE
    log_details := jsonb_build_object('deleted', to_jsonb(OLD));
  END IF;

  IF name_key IS NOT NULL AND friend_name IS NOT NULL AND friend_name <> '' THEN
    IF TG_OP = 'INSERT' THEN
      log_details := jsonb_build_object('inserted', to_jsonb(NEW) || jsonb_build_object(name_key, friend_name));
    ELSIF TG_OP = 'UPDATE' THEN
      log_details := jsonb_build_object(
        'before', to_jsonb(OLD) || jsonb_build_object(name_key, friend_name),
        'after',  to_jsonb(NEW) || jsonb_build_object(name_key, friend_name)
      );
    ELSE
      log_details := jsonb_build_object('deleted', to_jsonb(OLD) || jsonb_build_object(name_key, friend_name));
    END IF;
  END IF;

  INSERT INTO audit_log (action, table_name, record_id, origin_tab, device, details)
  VALUES (lower(TG_OP), TG_TABLE_NAME, subject_id, origin_tab, device, log_details);

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'audit_log trigger failed on %.% (%): %',
    TG_TABLE_NAME, TG_OP, SQLSTATE, SQLERRM;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ---- 12b. get_genre_ancestors(genre_id) ----
-- Recursive CTE that walks UP the genre_hierarchy from the given node to all
-- of its ancestor genres. Used by fn_genre_hierarchy_children and
-- fn_record_genres_refs. STABLE (no side effects, consistent within a tx).
CREATE OR REPLACE FUNCTION get_genre_ancestors(p_genre_id INT)
RETURNS TABLE(genre_id INT) AS $$
BEGIN
  RETURN QUERY
  WITH RECURSIVE ancestors AS (
    SELECT gh.parent_genre_id AS genre_id
    FROM genre_hierarchy gh
    WHERE gh.child_genre_id = p_genre_id
    UNION
    SELECT gh.parent_genre_id
    FROM genre_hierarchy gh
    JOIN ancestors a ON a.genre_id = gh.child_genre_id
  )
  SELECT DISTINCT a.genre_id FROM ancestors a;
END;
$$ LANGUAGE plpgsql STABLE;


-- ---- 12c. get_descriptor_ancestors(descriptor_id) ----
-- Same algorithm as get_genre_ancestors, for the descriptor tree.
CREATE OR REPLACE FUNCTION get_descriptor_ancestors(p_descriptor_id INT)
RETURNS TABLE(descriptor_id INT) AS $$
BEGIN
  RETURN QUERY
  WITH RECURSIVE ancestors AS (
    SELECT dh.parent_descriptor_id AS descriptor_id
    FROM descriptor_hierarchy dh
    WHERE dh.child_descriptor_id = p_descriptor_id
    UNION
    SELECT dh.parent_descriptor_id
    FROM descriptor_hierarchy dh
    JOIN ancestors a ON a.descriptor_id = dh.child_descriptor_id
  )
  SELECT DISTINCT a.descriptor_id FROM ancestors a;
END;
$$ LANGUAGE plpgsql STABLE;


-- ---- 12d. fn_record_artists_ref_count() ----
-- Direct ref_count on artists. Increments on INSERT, decrements on DELETE.
CREATE OR REPLACE FUNCTION fn_record_artists_ref_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE artists SET ref_count = ref_count + 1 WHERE artist_id = NEW.artist_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE artists SET ref_count = ref_count - 1 WHERE artist_id = OLD.artist_id;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12e. fn_record_genres_ref_count() ----
-- Direct ref_count on genres.
CREATE OR REPLACE FUNCTION fn_record_genres_ref_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE genres SET ref_count = ref_count + 1 WHERE genre_id = NEW.genre_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE genres SET ref_count = ref_count - 1 WHERE genre_id = OLD.genre_id;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12f. fn_record_descriptors_ref_count() ----
-- Direct ref_count on descriptors.
CREATE OR REPLACE FUNCTION fn_record_descriptors_ref_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE descriptors SET ref_count = ref_count + 1 WHERE descriptor_id = NEW.descriptor_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE descriptors SET ref_count = ref_count - 1 WHERE descriptor_id = OLD.descriptor_id;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12g. fn_genre_hierarchy_children() ----
-- Maintains children_count on genres when hierarchy edges change.
-- On INSERT of edge (parent -> child): for parent AND all of parent's ancestors,
-- increment children_count by 1 (the new child now sits under all of them).
-- On DELETE, the same loop decrements.
CREATE OR REPLACE FUNCTION fn_genre_hierarchy_children()
RETURNS TRIGGER AS $$
DECLARE
  aid INT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    FOR aid IN
      SELECT genre_id FROM get_genre_ancestors(NEW.parent_genre_id)
      UNION SELECT NEW.parent_genre_id
    LOOP
      UPDATE genres SET children_count = children_count + 1 WHERE genre_id = aid;
    END LOOP;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    FOR aid IN
      SELECT genre_id FROM get_genre_ancestors(OLD.parent_genre_id)
      UNION SELECT OLD.parent_genre_id
    LOOP
      UPDATE genres SET children_count = children_count - 1 WHERE genre_id = aid;
    END LOOP;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12h. fn_descriptor_hierarchy_children() ----
-- Same algorithm as fn_genre_hierarchy_children, for descriptors.
CREATE OR REPLACE FUNCTION fn_descriptor_hierarchy_children()
RETURNS TRIGGER AS $$
DECLARE
  aid INT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    FOR aid IN
      SELECT descriptor_id FROM get_descriptor_ancestors(NEW.parent_descriptor_id)
      UNION SELECT NEW.parent_descriptor_id
    LOOP
      UPDATE descriptors SET children_count = children_count + 1 WHERE descriptor_id = aid;
    END LOOP;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    FOR aid IN
      SELECT descriptor_id FROM get_descriptor_ancestors(OLD.parent_descriptor_id)
      UNION SELECT OLD.parent_descriptor_id
    LOOP
      UPDATE descriptors SET children_count = children_count - 1 WHERE descriptor_id = aid;
    END LOOP;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12i. fn_record_genres_refs() ----
-- Maintains total_ref_count on genres. When a record is linked to a genre,
-- every ancestor of that genre (plus the genre itself) gets total_ref_count += 1.
-- On DELETE, the same loop decrements. This is the inheritance rollup: a record
-- tagged with a leaf genre "counts" toward every ancestor.
CREATE OR REPLACE FUNCTION fn_record_genres_refs()
RETURNS TRIGGER AS $$
DECLARE
  gid INT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    FOR gid IN
      SELECT genre_id FROM get_genre_ancestors(NEW.genre_id)
      UNION SELECT NEW.genre_id
    LOOP
      UPDATE genres SET total_ref_count = total_ref_count + 1 WHERE genre_id = gid;
    END LOOP;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    FOR gid IN
      SELECT genre_id FROM get_genre_ancestors(OLD.genre_id)
      UNION SELECT OLD.genre_id
    LOOP
      UPDATE genres SET total_ref_count = total_ref_count - 1 WHERE genre_id = gid;
    END LOOP;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12j. fn_record_descriptors_refs() ----
-- Same algorithm as fn_record_genres_refs, for descriptors.
CREATE OR REPLACE FUNCTION fn_record_descriptors_refs()
RETURNS TRIGGER AS $$
DECLARE
  did INT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    FOR did IN
      SELECT descriptor_id FROM get_descriptor_ancestors(NEW.descriptor_id)
      UNION SELECT NEW.descriptor_id
    LOOP
      UPDATE descriptors SET total_ref_count = total_ref_count + 1 WHERE descriptor_id = did;
    END LOOP;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    FOR did IN
      SELECT descriptor_id FROM get_descriptor_ancestors(OLD.descriptor_id)
      UNION SELECT OLD.descriptor_id
    LOOP
      UPDATE descriptors SET total_ref_count = total_ref_count - 1 WHERE descriptor_id = did;
    END LOOP;
    RETURN OLD;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- ---- 12k. fn_verify_audit_triggers() ----
-- Read-only verification helper. Returns, for every expected data table,
-- whether the fn_audit_log trigger is attached and how many audit rows exist.
-- Called by the app's verify_audit_log probe via PostgREST rpc(). SECURITY
-- DEFINER lets the anonymous role read the catalogs; performs no writes.
CREATE OR REPLACE FUNCTION fn_verify_audit_triggers()
RETURNS TABLE(table_name TEXT, has_trigger BOOLEAN, rows_in_audit BIGINT) AS $$
DECLARE
  t   TEXT;
  expected TEXT[] := ARRAY[
    'records','artists','genres','descriptors',
    'record_artists','record_genres','record_descriptors',
    'record_streaming','genre_hierarchy','descriptor_hierarchy'
  ];
BEGIN
  FOREACH t IN ARRAY expected LOOP
    table_name := t;

    SELECT EXISTS (
      SELECT 1
      FROM pg_trigger trg
      JOIN pg_class c   ON c.oid = trg.tgrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_proc p    ON p.oid = trg.tgfoid
      WHERE n.nspname = 'public'
        AND c.relname = t
        AND p.proname = 'fn_audit_log'
        AND trg.tgname LIKE 'trg_audit_%'
    ) INTO has_trigger;

    SELECT COUNT(*) INTO rows_in_audit
    FROM public.audit_log a WHERE a.table_name = t;

    RETURN NEXT;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =============================================================================
-- 13. TRIGGERS  (17 triggers)
-- =============================================================================
-- Every data table has at least one audit trigger calling fn_audit_log().
-- Junction and hierarchy tables additionally have count-maintenance triggers.
-- Records + junction tables: audit triggers are attached but fn_audit_log()
-- skips them (app logs those as whole-tuple entries instead). The triggers
-- stay attached for potential future use (e.g. change detection).

-- -- records (audit only) --
DROP TRIGGER IF EXISTS trg_audit_records ON records;
CREATE TRIGGER trg_audit_records
  AFTER INSERT OR UPDATE OR DELETE ON records
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- -- artists (audit only) --
DROP TRIGGER IF EXISTS trg_audit_artists ON artists;
CREATE TRIGGER trg_audit_artists
  AFTER INSERT OR UPDATE OR DELETE ON artists
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- -- genres (audit + children_count trigger) --
DROP TRIGGER IF EXISTS trg_audit_genres ON genres;
CREATE TRIGGER trg_audit_genres
  AFTER INSERT OR UPDATE OR DELETE ON genres
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

DROP TRIGGER IF EXISTS trg_genre_hierarchy_children ON genre_hierarchy;
CREATE TRIGGER trg_genre_hierarchy_children
  AFTER INSERT OR DELETE ON genre_hierarchy
  FOR EACH ROW EXECUTE FUNCTION fn_genre_hierarchy_children();

-- -- descriptors (audit + children_count trigger) --
DROP TRIGGER IF EXISTS trg_audit_descriptors ON descriptors;
CREATE TRIGGER trg_audit_descriptors
  AFTER INSERT OR UPDATE OR DELETE ON descriptors
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

DROP TRIGGER IF EXISTS trg_descriptor_hierarchy_children ON descriptor_hierarchy;
CREATE TRIGGER trg_descriptor_hierarchy_children
  AFTER INSERT OR DELETE ON descriptor_hierarchy
  FOR EACH ROW EXECUTE FUNCTION fn_descriptor_hierarchy_children();

-- -- record_artists (audit + ref_count) --
DROP TRIGGER IF EXISTS trg_audit_record_artists ON record_artists;
CREATE TRIGGER trg_audit_record_artists
  AFTER INSERT OR UPDATE OR DELETE ON record_artists
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

DROP TRIGGER IF EXISTS trg_record_artists_ref_count ON record_artists;
CREATE TRIGGER trg_record_artists_ref_count
  AFTER INSERT OR DELETE ON record_artists
  FOR EACH ROW EXECUTE FUNCTION fn_record_artists_ref_count();

-- -- record_genres (audit + ref_count + total_ref_count) --
DROP TRIGGER IF EXISTS trg_audit_record_genres ON record_genres;
CREATE TRIGGER trg_audit_record_genres
  AFTER INSERT OR UPDATE OR DELETE ON record_genres
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

DROP TRIGGER IF EXISTS trg_record_genres_ref_count ON record_genres;
CREATE TRIGGER trg_record_genres_ref_count
  AFTER INSERT OR DELETE ON record_genres
  FOR EACH ROW EXECUTE FUNCTION fn_record_genres_ref_count();

DROP TRIGGER IF EXISTS trg_record_genres_refs ON record_genres;
CREATE TRIGGER trg_record_genres_refs
  AFTER INSERT OR DELETE ON record_genres
  FOR EACH ROW EXECUTE FUNCTION fn_record_genres_refs();

-- -- record_descriptors (audit + ref_count + total_ref_count) --
DROP TRIGGER IF EXISTS trg_audit_record_descriptors ON record_descriptors;
CREATE TRIGGER trg_audit_record_descriptors
  AFTER INSERT OR UPDATE OR DELETE ON record_descriptors
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

DROP TRIGGER IF EXISTS trg_record_descriptors_ref_count ON record_descriptors;
CREATE TRIGGER trg_record_descriptors_ref_count
  AFTER INSERT OR DELETE ON record_descriptors
  FOR EACH ROW EXECUTE FUNCTION fn_record_descriptors_ref_count();

DROP TRIGGER IF EXISTS trg_record_descriptors_refs ON record_descriptors;
CREATE TRIGGER trg_record_descriptors_refs
  AFTER INSERT OR DELETE ON record_descriptors
  FOR EACH ROW EXECUTE FUNCTION fn_record_descriptors_refs();

-- -- record_streaming (audit only) --
DROP TRIGGER IF EXISTS trg_audit_record_streaming ON record_streaming;
CREATE TRIGGER trg_audit_record_streaming
  AFTER INSERT OR UPDATE OR DELETE ON record_streaming
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- -- genre_hierarchy (audit + children_count) --
DROP TRIGGER IF EXISTS trg_audit_genre_hierarchy ON genre_hierarchy;
CREATE TRIGGER trg_audit_genre_hierarchy
  AFTER INSERT OR UPDATE OR DELETE ON genre_hierarchy
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();

-- -- descriptor_hierarchy (audit + children_count) --
DROP TRIGGER IF EXISTS trg_audit_descriptor_hierarchy ON descriptor_hierarchy;
CREATE TRIGGER trg_audit_descriptor_hierarchy
  AFTER INSERT OR UPDATE OR DELETE ON descriptor_hierarchy
  FOR EACH ROW EXECUTE FUNCTION fn_audit_log();


-- =============================================================================
-- 14. GRANTS
-- =============================================================================
-- The anonymous role (used by the Flutter web app via the anon key) has full
-- DML access to all public tables. The authenticated and service_role roles
-- have the same access. This is the default Supabase pattern: access control
-- is managed at the application level (RLS), not at the grant level.
--
-- Current RLS status: NO tables have RLS enabled (see section 15 for the
-- deferred audit_log hard-lock). All access is governed by the GRANTs alone.

-- All four roles get full DML on every table. The pattern is:
--   GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
--   ON <table> TO <role>;
-- Applied to: anon, authenticated, postgres, service_role
-- Applied to: artists, records, genres, descriptors, record_artists,
--   record_genres, record_descriptors, record_streaming, genre_hierarchy,
--   descriptor_hierarchy, audit_log


-- =============================================================================
-- 15. RLS NOTES  (audit_log hard-lock, DEFERRED)
-- =============================================================================
-- The audit_log table should eventually be locked to INSERT-only (no client
-- can UPDATE or DELETE rows). This is achieved by:
--
--   ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
--
--   -- Block all SELECTs (logs are never read via the DB; they're read via
--   -- PostgREST/anon, and the app never needs to SELECT from audit_log).
--   CREATE POLICY audit_log_block_all ON audit_log
--     FOR SELECT USING (false);
--
--   -- Allow INSERTs only (the SECURITY DEFINER trigger bypasses RLS, and
--   -- the client's app_boot insert also needs INSERT).
--   CREATE POLICY audit_log_insert_anon ON audit_log
--     FOR INSERT WITH CHECK (true);
--
--   -- No UPDATE policy -> denied for all non-owner roles.
--   -- No DELETE policy -> denied for all non-owner roles.
--
-- This is deliberately DEFERRED until the audit log has been verified correct
-- via the app's verify_audit_log probe. The SQL for this lives in:
--   phase 6 deployment/temp rls/supabase_migration_audit_log_rls.sql
--
-- Why SECURITY DEFINER still works after RLS is enabled:
--   fn_audit_log() is SECURITY DEFINER, meaning it runs as the function owner
--   (postgres), not as the calling role. The owner bypasses RLS entirely, so
--   the trigger can still write log rows even after RLS is turned on. Only
--   direct client UPDATE/DELETE is blocked.
-- =============================================================================
